name: tmc_smiles_ml
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.3.5
  - aiohttp=3.10.1
  - aiosignal=1.3.1
  - aom=3.9.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.6.2
  - ffmpeg=7.0.1
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - greenlet=3.0.3
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.5
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.122
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenvino=2024.1.0
  - libopenvino-auto-batch-plugin=2024.1.0
  - libopenvino-auto-plugin=2024.1.0
  - libopenvino-hetero-plugin=2024.1.0
  - libopenvino-intel-cpu-plugin=2024.1.0
  - libopenvino-intel-gpu-plugin=2024.1.0
  - libopenvino-intel-npu-plugin=2024.1.0
  - libopenvino-ir-frontend=2024.1.0
  - libopenvino-onnx-frontend=2024.1.0
  - libopenvino-paddle-frontend=2024.1.0
  - libopenvino-pytorch-frontend=2024.1.0
  - libopenvino-tensorflow-frontend=2024.1.0
  - libopenvino-tensorflow-lite-frontend=2024.1.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.21.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - munkres=1.1.4
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.0
  - openssl=3.3.1
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.43
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pugixml=1.14
  - pycairo=1.26.1
  - pycparser=2.22
  - pyg=2.5.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - rdkit=2024.03.3
  - readline=8.2
  - reportlab=4.2.2
  - requests=2.32.3
  - rlpycairo=0.2.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlalchemy=2.0.32
  - svt-av1=2.1.0
  - sympy=1.13.0
  - tbb=2021.12.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - torchvision=0.15.2
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wayland=1.23.0
  - wayland-protocols=1.36
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - alembic==1.13.2
      - click==8.1.7
      - colorlog==6.8.2
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hydgl==0.1
      - lightgbm==4.5.0
      - lightning-utilities==0.11.7
      - mako==1.3.5
      - matplotlib==3.9.1.post1
      - optuna==3.6.1
      - optuna-integration==3.6.0
      - platformdirs==4.2.2
      - protobuf==5.27.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - torchmetrics==1.4.2
      - wandb==0.17.6
